### PR TITLE
Use meson to build extension

### LINKED ISSUE #8: Request for help: Upgrade `okada_wrapper` to work with Python 3.12 and up.
`numpy.distutils` has been deprecated and this will kill `okada_wrapper` as currently written

See the discussion and explanations here:
- https://github.com/kmaterna/Elastic_stresses_py/issues/15#
- https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration

If someone wants to migrate `okada_wrapper` to build with scikit-build/CMake or Meson as explained in the link above, I would be happy to give you assistance. But I don't have time to lead that effort.

### PR DESCRIPTION
**Pull request by tobiscode**
Hi,
I was able to track the error to some unintuitive (or buggy) behavior in how `meson` and/or `f2py` use the `.pyf` file. Specifically, it seems that the part where it specifies the output of the `DC3D(0)` functions is at least partially ignored. By adding the intent as a comment into the source `.f` file, the expected behavior is restored. (I'm not sure whether the `.pyf` file is still needed, but I kept it in for now.)
I took the liberty of addressing some linter messages and removing the LaTeX dependency for `test_okada.py` to make it easier for people to test everything, please feel free to ignore these parts of the PR if desired.
I hope this fixes https://github.com/tbenthompson/okada_wrapper/issues/8 ; I've tested it with Python 3.12 myself and the installation and and `test_okada.py` work now.
Cheers

### CODE REVIEW

**Comment by tobiscode** [comment]
Oh, I didn't change the version number, that's maybe something to consider to make it clearer for `pip` installations to see it was updated and now has different requirements.

**Comment by brendanjmeade** [comment]
Wow!  This is fantastic.  Is it the python version that needs to be updated in environment.yml?  Something else?

**Comment by tbenthompson** [comment]
@tobiscode  This is fantastic!! Thank you so much. I'm going to give this PR a look over as soon as I can but I'll probably just merge it. Then I'll release a new version. It might be this week but it might take until this weekend because I'm on a work trip and it's quite busy.

@brendanjmeade If I remember correctly, there are several places. environment.yml and setup.py come to mind.

**Comment by tbenthompson** [comment]
Ok, I got excited and looked through! All great stuff. Thanks again.

**Comment by tobiscode** [comment]
Awesome! Since `setup.py` isn't a thing anymore, the only place to update the package version is `pyproject.toml` (`version = "18.12.08.3"`). For the users, nothing should change since all changes are backwards-compatible / enforced by the use of the meson backend, so the part `requires-python = ">=3.8"` inside `pyproject.toml` can probably just stay. I don't see an `environment.yml` file but that is probably also fine.

**Comment by brendanjmeade** [comment]
Thanks Tobias!  That makes a lot of sense.

**Pull request merged**
